name: to zip

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '34523859+nudoing@users.noreply.github.com'
      - name: Create Tag
        run: |
          git tag resourcepack
          git push resourcepack
      - name: archive release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: '.'
          filename: 'release.zip'
          exclusions: '*.git* .vscore/* release.zip'

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          name: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


