name: to zip

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: archive release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: '.'
          filename: 'release.zip'
          exclusions: '*.git* .vscore/* release.zip'

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          name: release.zip


